### ISSUE TITLE
Fonctionnalite : faire valider les prises de notes par le créateur de la note (javascript)

### ISSUE THREAD

**Issue by antonin-durey** [KaranteDeux/Projet_IHM#12]

**Comment by momo59k** [comment]
Dans cette fonctionnalité le créateur peut valider la modification d'une note par les autres utilisateurs car c'est lui qui l'a crée. Donc si on se retrouve sur l'écran des notes, avec par exemple une note 
"12-03-2015 - IHM - You". Je peut mettre par exemple une partie du texte surligné ce qui veut dire qu'elle a été modifié. Lorsque le créateur clique sur valider note (rajouter une option parmi les Editors, Manage, rate...) il valide la note et du coup le texte n'est plus surligné ? Qu'en pensez-vous ? Je fais comme ça c'est pas mal non ?

**Comment by antonin-durey** [comment]
Oui par exemple. Ca me semble une bonne idée

**Comment by Wassim24** [comment]
Ce que je propose c'est de mettre une check icon a côté de Card title et que quand il clique sur cette check icon il valide.

Petite image pour illustrer :

![test](https://cloud.githubusercontent.com/assets/9412806/14364034/458ec584-fd07-11e5-9aba-3293d765a112.jpg)

Un truc du genre, une icone qui illustre le fait qu'il y ait eu une modif, ensuite juste un clilk dessus valide quoi.

**Comment by momo59k** [comment]
Oe c'est super ! Ok je vais essayer de faire ça, du coup on garde le principe qui consiste à surligner le texte modifier et lorsque l'on clique sur le "check" à coté de card title on valide. Je vais prendre une note dans index.html et je fais ça !

**Comment by Wassim24** [comment]
Oué c'est ça !

**Comment by momo59k** [comment]
Voilà normalement c'est fait comme prévu !
