### ISSUE TITLE
Répartition présentation

### ISSUE THREAD

**Issue by antonin-durey** [KaranteDeux/Projet_IHM#14]
- Wassim :
  - Intro (ce qu'est l'appli : réseau social de prise de note)
  - Agencement générale de l'interface utilisateur
- Nabil :
  - Profil (info, amis et stats)
  - Création de note (et édition)
- Antonin :
  - Notion de note partagée (exliquer ce que c'est, exemple..)
  - Voir les noteurs d'une note, en ajouter
- Mohamed : 
  - Validation (par le créateur)
  - Noter les notes
  - Champ de recherche et tri par option/thème
- Nabil
  - Envoyer la note par wifi/bluetooth...
  - Partager des notes
- Antonin
  - Map
- Wassim :
  - Conclusion

**Comment by Wassim24** [comment]
Voici le lien de la vidéo : https://drive.google.com/open?id=0B7sgBke7PP77U1BNaXA4dTczUVE
@KaranteDeux  @momo59k  @NabilMaiz

**Comment by momo59k** [comment]
Super, et quel acteur je fais ! Je mérite un oscar xD

**Comment by Wassim24** [comment]
Effectivement XD
