### ISSUE TITLE
Ecran : afficher une note

### ISSUE THREAD

**Issue by antonin-durey** [KaranteDeux/Projet_IHM#3]

**Comment by momo59k** [comment]
Ok nice ! Donc du coup tu as intégré ce que je fais directement dans la carte ! En mode par exemple "12-03-2015 - M3DS - You". C'est plus simple je l'avoue :p 
Du coup le tri des notes est aussi terminé j'imagine où est-ce que l'on devrait rajouter des critères ?

**Comment by Wassim24** [comment]
Je sais pas peut être je vais les mettre sur le side bar, mais pas sûr. Je
verrais après, mais bon !

**Comment by momo59k** [comment]
Je vois que maintenant on a un menu en bas à droite où on peut trier les notes selon les matières. J'ai modifié la date sur les les notes comme ça on peut voir qu'il sont triés selon la matière et selon la date.  
On peut aussi rajouter l'auteur de la note à moins que l'on laisse que des "you" sur les notes ? Mais c'est déjà très bien comme ça on peut garder ce qu'on a fait !
