### ISSUE TITLE
Fonctionnalite : liste des notes (tri selon différents critères) (javascript)

### ISSUE THREAD

**Issue by antonin-durey** [KaranteDeux/Projet_IHM#5]

**Comment by momo59k** [comment]
Normalement les notes sont maintenant triées selon le cours, auteur et date. Regardez si c'est bien cela qu'on voulait obtenir, après je ferme ce ticket :)

**Comment by antonin-durey** [comment]
ça m'a lair bon

**Comment by momo59k** [comment]
Ok super !
