### ISSUE TITLE
Fonctionnalite : de recherche avec recherche dans les notes de l'utilisateur et dans les notes libres (recherche par auteur/catégorie/dossier/date/thème)(javascript)

### ISSUE THREAD

**Issue by antonin-durey** [KaranteDeux/Projet_IHM#6]

**Comment by momo59k** [comment]
Pour la barre de recherche, l'ouverture de la barre lorsque l'on clique sur le rond de recherche ne fonctionne pas. C'est normal ? Est-ce que je dois corriger et faire marcher le slide de la barre de recherche ou est-ce qu'il y a un bug ?

**Comment by momo59k** [comment]
Alors j'ai ajouté la recherche par mot clé dans index.html. Appuyer sur l'icone recherche une fois pour la faire défiler une deuxième fois pour la remettre à son état de base..
Pour recherche un mot appuyer sur la touche Entrer du clavier. 
On recherche pour l'instant en fonction du cours et de la date. Les mots clé à taper (minuscule ou majuscule) :

car
ihm
svl
m3ds
all
08-03-2015
12-03-2015
...

On peut rajouter d'autres options de recherche si vous voulez après ? Ou c'est bon pour vous comme ça ?

**Comment by antonin-durey** [comment]
ça m'a l'air bon comme ça. Enfin c'est déjà très bien ce qui est fait

**Comment by momo59k** [comment]
Ok je ferme le ticket !
